Develop
KernTHeAce/test_task pull request #1
Opened 2022-01-11 12:59 UTC by KernTHeAce

SRS was created and edited

2022-01-11 14:07 UTC, commanderprice commented on SRS.md
> +![image](https://user-images.githubusercontent.com/64127128/148945647-0cff4242-0645-47b1-8e52-2ac22bca8937.png)
Can you please save all screenshots in a folder inside repository and take them from it?

2022-01-11 14:16 UTC, KernTHeAce commented on SRS.md
> +![image](https://user-images.githubusercontent.com/64127128/148945647-0cff4242-0645-47b1-8e52-2ac22bca8937.png)
Done

2022-01-14 10:18 UTC, commanderprice commented on SRS.md
> +![image](https://user-images.githubusercontent.com/64127128/148945647-0cff4242-0645-47b1-8e52-2ac22bca8937.png)
I also wanted you to provide links in a relative way (e.g. [./screenshots/img1.png]), not links to images stored at GitHub servers. Also I see only two images, while every use case should have them

2022-01-14 10:26 UTC, commanderprice commented on SRS.md
> +
In the last step, what do you mean by form *with updated data*?

2022-01-14 10:27 UTC, commanderprice requested changes
Okay, first of all, example of software specification wasn't meant to be a Ctrl+C/Ctrl+V template, it's just an example of what you can write and it's even not complete. Plus in attached links to this step you can find a list of possible sections of SRS.

Secondly, current SRS has a lot of mistakes from English language point of view. I won't search and point at all of them, you'll have to work it out yourself. Here are some of mistakes I found:
* The _mod_ is designed → missing letter
* User select → `missing `s` at the end of verbs
* identificator → identifier
* employees salary → `employee's` or `employees` depending on what you meant, read about possessive case
* incorrect data massage are displayed → m**e**ssage *is* displayed or m**e**ssages *are* displayed
* When adding a employee → `an employee`, remember about articles

2022-01-20 14:13 UTC, commanderprice commented on SRS.md
> +specified period.
> display the number of employees for specified period

What does this mean?

2022-01-20 14:14 UTC, commanderprice commented on SRS.md
> +* Department - department, where employees work;
I guess it should be `employee works`

2022-01-20 14:15 UTC, commanderprice commented on SRS.md
> +* If any data is entered incorrectly, the incorrect data message is displayed;
> the incorrect data message is displayed

I read this as `the message is displayed and this message is incorrect`

2022-01-20 14:17 UTC, commanderprice commented on SRS.md
> +* Data don't save in database, then the list of employees records is displaying to a user.
`don't save`, `is displaying` — wrong, use passive voice

2022-01-20 14:17 UTC, commanderprice commented on SRS.md
> +* Id - identification of employee;
here and below

2022-01-20 14:18 UTC, commanderprice commented on SRS.md
> +* Department - department, where employees work;
here and below

2022-01-20 14:18 UTC, commanderprice commented on SRS.md
> +* If any data is entered incorrectly, the incorrect data message is displayed;
here and below

2022-01-20 14:19 UTC, commanderprice commented on SRS.md
> +* If entered data is valid, then edited is adding to the database;
> then edited is adding to the database

I don't really get the meaning of this part

2022-01-20 14:20 UTC, commanderprice commented on SRS.md
> +* If employee record is successfully edited, then the list of employees with added records is displayed.
And what happens if it wasn't successfully edited? Moreover, why can it be not a success if on previous step we checked that entered data is valid?

2022-01-20 14:22 UTC, commanderprice commented on SRS.md
> +* Data don't save in database, then the list of employees records is displaying to a user.
here and below

2022-01-20 14:23 UTC, commanderprice commented on SRS.md
> +
What happens otherwise?

2022-01-20 14:24 UTC, commanderprice commented on SRS.md
> +
> the list of employees with deleted records is displayed

Do we store deleted records?

2022-01-20 14:24 UTC, commanderprice commented on SRS.md
> +### 1.5 Filtering emploees by date
employees

2022-01-20 14:26 UTC, commanderprice commented on SRS.md
> +* Application displayslist of Employees.
missed space

2022-01-20 14:27 UTC, commanderprice commented on SRS.md
> +* After manipulations with these records the user clicks the "Back" button.
Is this the only way `Back` button is used? If so, in my opinion it's name doesn't really explain what it does

2022-01-20 14:28 UTC, commanderprice commented on SRS.md
> +* Application displayslist of Employees.
How is this different from main path?

2022-01-20 14:29 UTC, commanderprice commented on SRS.md
> +* After manipulations with these records the user clicks the "Back" button.
Oh, okay, nevermind, let it be

2022-01-20 14:30 UTC, commanderprice commented on SRS.md
> +
How is this different from main path?

2022-01-20 14:30 UTC, commanderprice commented on SRS.md
> +The mod is designed to view the list of departments if it is possible to display the number of departments for
`mode`

2022-01-20 14:31 UTC, commanderprice commented on SRS.md
> +The mod is designed to view the list of departments if it is possible to display the number of departments for
> for specified period

Again, copypaste from template

2022-01-20 14:34 UTC, commanderprice commented on SRS.md
> +* If a new department record is successfully added, then the list of departments with added records is displayed.
Here and below (if there is similar stuff): what happens if a new department record is *not* successfully added and how this can happen if on previous step we checked the data?

2022-01-20 14:37 UTC, commanderprice commented on SRS.md
> +Pic. 2.3 Edit department.
🙄

2022-01-20 14:38 UTC, commanderprice commented on SRS.md
> +* If the department record is successfully deleted, then the list of departments without deleted records is displayed.
What happens if there are employees attached to this department?

2022-01-20 14:39 UTC, commanderprice commented on SRS.md
> +This application is supported on all types of devices, with different screen resolutions. This is possible thanks to adapyive layout.
adapyive

2022-01-28 12:12 UTC, KernTHeAce commented on SRS.md
> +* The list of employees with added records is displayed.
I replace it with : 
* If any data is entered incorrectly, the "Incorrect Data" message is displayed. You should enter correct data and press the "Save" button or press the "Cancel" button;

is that correct?

2022-01-28 12:31 UTC, commanderprice requested changes

2022-01-28 12:31 UTC, commanderprice commented on SRS.md
> +* If any data is entered incorrectly, the "Incorrect Data" message is displayed. You should enter correct data and press the "Save" button or press the "Cancel" button;
Here and below: not `you` but `user` and after `press the "Cancel" button` I would either reference Cancel operation scenario or describe what happens after pressing Cancel button

2022-01-28 12:46 UTC, KernTHeAce commented on SRS.md
> +* If any data is entered incorrectly, the "Incorrect Data" message is displayed. You should enter correct data and press the "Save" button or press the "Cancel" button;
By link you mean something like that?
>... or press the "Cancel" button(see "Cancel operation scenario");

2022-01-28 12:48 UTC, commanderprice approved these changes

2022-01-28 12:49 UTC, merged