Develop
KernTHeAce/test_task pull request #2
Opened 2022-01-28 18:37 UTC by KernTHeAce

2022-02-01 13:55 UTC, commanderprice requested changes

2022-02-01 13:55 UTC, commanderprice commented on templates/departments.html
> +            </div>
Check your links everywhere please🙃

2022-02-01 13:57 UTC, commanderprice commented
Also, according to task you were supposed to create your prototype inside `/documentation/html_prototype`, read tasks carefully please

2022-02-01 14:01 UTC, KernTHeAce commented on templates/departments.html
> +            </div>
So, what's wrong with links&

2022-02-01 14:13 UTC, KernTHeAce commented on templates/departments.html
> +    <link rel="stylesheet" href="E:/python_code/epam_task/static/css/reset.css" />
Done

2022-02-01 14:17 UTC, commanderprice commented on templates/departments.html
> +    <link rel="stylesheet" href="E:/python_code/epam_task/static/css/reset.css" />
Good, now you need to fix the rest of the links

2022-02-01 14:19 UTC, KernTHeAce commented on templates/departments.html
> +            </div>
okay, I understood)

2022-02-01 14:28 UTC, KernTHeAce commented on templates/departments.html
> +            </div>
Done

2022-02-01 14:37 UTC, commanderprice requested changes

2022-02-01 14:37 UTC, commanderprice commented on documentation/html_prototype/templates/filter.html
> +            </div>
Here and in `Find`: why use text input when we have date picker?

2022-02-01 14:37 UTC, commanderprice commented on documentation/html_prototype/templates/new_dep.html
> +                            <input class="input" type="text" placeholder="Department" />
Here we can describe limitations for this field

2022-02-01 14:37 UTC, commanderprice commented on documentation/html_prototype/templates/new_empl.html
> +                        </div>
Here we can use different type of inputs too. And we can describe fields limitations here as well

2022-02-01 14:50 UTC, commanderprice commented on documentation/html_prototype/templates/new_empl.html
> +                        </div>
Okay, when I said `different type of inputs` I didn't mean just the date picker. Can you think of more options for other fields?

2022-02-01 15:05 UTC, KernTHeAce commented on documentation/html_prototype/templates/new_empl.html
> +                        </div>
I think, that the 'Name' and the 'Department' fields should be 'text' type. I also added 'maxlength' attribute to these inputs.
The 'Salary' field now has 'number' type and also has the 'step' attribute according to srs.

2022-02-01 15:06 UTC, KernTHeAce commented on documentation/html_prototype/templates/new_empl.html
> +                        </div>
![image](https://user-images.githubusercontent.com/64127128/151993910-308fb771-f1b5-4a67-8bff-9264eae24021.png)

2022-02-02 07:04 UTC, commanderprice approved these changes

2022-02-02 07:06 UTC, commanderprice commented on documentation/html_prototype/templates/new_empl.html
> +                        </div>
> I think, that the 'Name' *and the 'Department'* fields should be 'text' type

Wouldn't it be more convenient and less error-prone to have ability to choose department from a list of existing departments rather than to enter its name manually?

2022-02-02 11:40 UTC, commanderprice commented
I was reviewing your SRS again and got a new question. Can you explain, why in constraints lists, like this one:
```
Id - maximum length of 4 digits;
Employee Full Name - maximum length of 60 characters;
Department - maximum length of 45 characters;
Birth date - date in format dd/mm/yy;
Salary - maximum length of 8 digits.
```
you set such a constraint for `Id`?

2022-02-02 13:06 UTC, KernTHeAce commented
> I was reviewing your SRS again and got a new question. Can you explain, why in constraints lists, like this one:
> 
> ```
> Id - maximum length of 4 digits;
> Employee Full Name - maximum length of 60 characters;
> Department - maximum length of 45 characters;
> Birth date - date in format dd/mm/yy;
> Salary - maximum length of 8 digits.
> ```
> 
> you set such a constraint for `Id`?

I think, that every field should have some constraints. At all, I  don't sure, that this application was created for supporting work with so large database

2022-02-02 13:29 UTC, commanderprice commented
> every field should have some constraints

Perhaps, but is `Id` something that is provided by user?

2022-02-02 13:45 UTC, commanderprice commented
What I'm trying to say is that if by setting constraint `Id - maximum length of 4 digits;` you want to say `The application will be capable to store up to 10 000 persons` then this is what you should write in a separate section

2022-02-02 13:47 UTC, KernTHeAce commented
> > every field should have some constraints
> 
> Perhaps, but is `Id` something that is provided by user?

In my plans, it's just a serial number

2022-02-02 13:51 UTC, KernTHeAce commented
> What I'm trying to say is that if by setting constraint `Id - maximum length of 4 digits;` you want to say `The application will be capable to store up to 10 000 persons` then this is what you should write in a separate section

You means separate section of srs?

2022-02-02 13:51 UTC, commanderprice commented
Yes

2022-02-02 14:07 UTC, merged